In [26]:
import pandas as pd
def create_dataframe(data, columns):
    df = pd.DataFrame(data, columns=columns)
    return df
def filter_dataframe(df, column, value):
    filtered_df = df[df[column] == value]
    return filtered_df
def sort_dataframe(df, column):
    sorted_df = df.sort_values(by=column)
    return sorted_df 
def test():
    data = [
        [4, 'David Border', 45],
        [1, 'Alice and Wonderland', 3],
        [3, 'Charles Chickens', 23546453635],
        [2, 'Bob', -1]

    ]
    columns = ['ID', 'Name', 'Age']
    df = create_dataframe(data, columns)
    print("Original DataFrame:")
    print(df)
    sorted_df = sort_dataframe(df, 'Name')
    print("\nSorted DataFrame by Name:")
    return sorted_df
a =test()
a

Original DataFrame:
   ID                  Name          Age
0   4          David Border           45
1   1  Alice and Wonderland            3
2   3      Charles Chickens  23546453635
3   2                   Bob           -1

Sorted DataFrame by Name:

   ID                  Name          Age
1   1  Alice and Wonderland            3
3   2                   Bob           -1
2   3      Charles Chickens  23546453635
0   4          David Border           45

In [29]:
import pandas as pd
sdata = pd.read_csv('team.csv')
sdata.loc[sdata["Occupation"] == "Time Traveler"]

,Name,Age,Occupation,Favorite Color,Number of Socks,Owns a Unicorn
2,Ferdinand,102,Time Traveler,Invisible,3,False

In [30]:
import pandas as pd
data = pd.read_csv('lengchu.csv')
data_features = ["Rooms", "Bathroom", "Landsize"]
data[data_features]

       Rooms  Bathroom  Landsize
0          2       1.0     202.0
1          2       1.0     156.0
2          3       2.0     134.0
3          3       2.0      94.0
4          4       1.0     120.0
...      ...       ...       ...
13575      4       2.0     652.0
13576      3       2.0     333.0
13577      3       2.0     436.0
13578      4       1.0     866.0
13579      4       1.0     362.0

[13580 rows x 3 columns]